### ISSUE TITLE
Incorrectly flagging line breaks in media rulesets as error

### ISSUE THREAD

**Issue by simonsmith** [suitcss/stylelint-config-suitcss#6]
This common pattern in many SUIT utils shows as an error:

``` css
@media (--sm-viewport) {
x <-- this line is an error
  .u-sm-afterNone {
    margin-left: 0 !important;
  }

}
```

I can fix it by setting:

``` js
    "rule-nested-empty-line-before": "always-multi-line"
```

@jeddy3 Before I change it just wanted to know if there is something I've missed as to why it had `except: ["first-nested"]`? Cheers
